// Auth constants
export const LOGIN = "LOGIN";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const SIGNUP_COMPLETED = "SIGNUP_COMPLETED";
export const REMOVE_AUTH_TOAST = "REMOVE_AUTH_TOAST";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const GET_RESET_PASSWORD_OTP = "GET_RESET_PASSWORD_OTP";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS_MESSAGE = "RESET_PASSWORD_SUCCESS_MESSAGE";
export const RESET_PASSWORD_ERROR_MESSAGE = "RESET_PASSWORD_ERROR_MESSAGE";

// Friendship constants
export const GET_FRIEND_REQUESTS = "GET_FRIEND_REQUESTS";
export const GET_FRIEND_REQUESTS_COMPLETED = "GET_FRIEND_REQUESTS_COMPLETED";
export const GET_FRIEND_REQUESTS_ERROR = "GET_FRIEND_REQUESTS_ERROR";

export const GET_SENT_FRIEND_REQUESTS = "GET_SENT_FRIEND_REQUESTS";
export const GET_SENT_FRIEND_REQUESTS_COMPLETED = "GET_SENT_FRIEND_REQUESTS_COMPLETED";
export const GET_SENT_FRIEND_REQUESTS_ERROR = "GET_SENT_FRIEND_REQUESTS_ERROR";

export const GET_FRIEND_LIST = "GET_FRIEND_LIST";
export const GET_FRIEND_LIST_COMPLETED = "GET_FRIEND_LIST_COMPLETED";
export const GET_FRIEND_LIST_ERROR = "GET_FRIEND_LIST_ERROR";

export const GET_SUGGESTED_FRIENDS = "GET_SUGGESTED_FRIENDS";
export const GET_SUGGESTED_FRIENDS_COMPLETED = "GET_SUGGESTED_FRIENDS_COMPLETED";
export const GET_SUGGESTED_FRIENDS_ERROR = "GET_SUGGESTED_FRIENDS_ERROR";

export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
export const SEND_FRIEND_REQUEST_COMPLETED = "SEND_FRIEND_REQUEST_COMPLETED";
export const SEND_FRIEND_REQUEST_ERROR = "SEND_FRIEND_REQUEST_ERROR";

export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const ACCEPT_FRIEND_REQUEST_COMPLETED = "ACCEPT_FRIEND_REQUEST_COMPLETED";
export const ACCEPT_FRIEND_REQUEST_ERROR = "ACCEPT_FRIEND_REQUEST_ERROR";

export const REJECT_FRIEND_REQUEST = "REJECT_FRIEND_REQUEST";
export const REJECT_FRIEND_REQUEST_COMPLETED = "REJECT_FRIEND_REQUEST_COMPLETED";
export const REJECT_FRIEND_REQUEST_ERROR = "REJECT_FRIEND_REQUEST_ERROR";

export const CANCEL_FRIEND_REQUEST = "CANCEL_FRIEND_REQUEST";
export const CANCEL_FRIEND_REQUEST_COMPLETED = "CANCEL_FRIEND_REQUEST_COMPLETED";
export const CANCEL_FRIEND_REQUEST_ERROR = "CANCEL_FRIEND_REQUEST_ERROR";

export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const REMOVE_FRIEND_COMPLETED = "REMOVE_FRIEND_COMPLETED";
export const REMOVE_FRIEND_ERROR = "REMOVE_FRIEND_ERROR";

// Chat constants
export const GET_RECENT_CHATS = "GET_RECENT_CHATS"
export const GET_RECENT_CHATS_COMPLETED = "GET_RECENT_CHATS_COMPLETED"
export const GET_RECENT_CHATS_ERROR = "GET_RECENT_CHATS_ERROR"
export const SEND_MESSAGE = "SEND_MESSAGE"
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR"
export const GET_USER_FRIEND_MESSAGES = "GET_USER_FRIEND_MESSAGES"
export const GET_USER_FRIEND_MESSAGES_COMPLETED = "GET_USER_FRIEND_MESSAGES_COMPLETED"
export const GET_USER_FRIEND_MESSAGES_ERROR = "GET_USER_FRIEND_MESSAGES_ERROR"
export const UPDATE_USER_FRIEND_CHAT = "UPDATE_USER_FRIEND_CHAT"

// Notification constants

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS"
export const SET_NOTIFICATIONS_ERROR = "SET_NOTIFICATIONS_ERROR"

export const READ_ALL_NOTIFICATIONS = "READ_ALL_NOTIFICATIONS"

