export const notifications = [
  "hello i am your new friend. wanna join me",
  "you are followed by",
  "dear user your pic has been uploaded",
  " your pic liked by",
  "hello i am your new friend. wanna join me",
  "you are followed by",
  "dear user your pic has been uploaded",
  " your pic liked by",
  "hello i am your new friend. wanna join me",
  "you are followed by",
  "dear user your pic has been uploaded",
  " your pic liked by",
  "hello i am your new friend. wanna join me",
  "you are followed by",
  "dear user your pic has been uploaded",
  " your pic liked by",
  "hello i am your new friend. wanna join me",
  "you are followed by",
  "dear user your pic has been uploaded",
  " your pic liked by",
];
